name: Build Ultimate GD Toolkit
'on':
workflow_dispatch:
push:
branches:
- main

jobs:
build:
runs-on: ubuntu-24.04
step:
- name: Checkout
uses: actions/checkout@v4

  - name: Build Geode mod
    uses: geode-sdk/build-geode-mod@main
    with:
      target: Android64
      sdk: given
      cli: latest
      path: ./
      build-config: Release
      use-lto: false
